version: '2'

services:

  postgres:
    restart: always
    container_name: postgres
    image: postgres:latest
    volumes_from:
      - data
    volumes:
      #- ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./backups/postgresql:/backup
    env_file:
      - .env
    # expose:
    # - "5432"

  data:
    restart: always
    container_name: data
    image: alpine
    volumes:
      - /var/lib/postgresql
    command: "true"

  web:
    # reminder to migrate sudo docker-compose run web /data/web/manage.py migrate
    # reminder to collecstatics sudo docker-compose run web /data/web/manage.py collectstatic
    restart: always
    container_name: djangominimal
    env_file: .env
    build: ./web
    # command: bash -c "while ! nc -w 1 -z postgres 5432; do sleep 0.1; done; ./manage.py migrate; while :; do ./manage.py runserver 0.0.0.0:8000; sleep 1; done"
    command: gunicorn djangominimal.wsgi:application -w 2 -b :8000
    ports:
      - "8000:8000"
    volumes:
      - ./web:/data/web
    depends_on:
      - postgres

  nginx:
    restart: always
    container_name: nginx
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - web
    links:
      - web:web
